#!/bin/sh
sed 's/,/./g' 45.csv | sed 's/\t/: [/' | sed 's/\t/, /' | sed 's/$/],/' > 45.cjs
sed 's/,/./g' 60.csv | sed 's/\t/: [/' | sed 's/\t/, /' | sed 's/$/],/' >60.cjs
sed 's/,/./g' 90.csv | sed 's/\t/: [/' | sed 's/\t/, /' | sed 's/$/],/' >90.cjs
sed 's/,/./g' 120.csv | sed 's/\t/: [/' | sed 's/\t/, /' | sed 's/$/],/' >120.cjs


sed 's/,/./g' 45_rs.csv | sed 's/\t/: [/' | sed 's/\t/, /' | sed 's/$/],/' > 45_rs.cjs
sed 's/,/./g' 60_rs.csv | sed 's/\t/: [/' | sed 's/\t/, /' | sed 's/$/],/' > 60_rs.cjs
sed 's/,/./g' 90_rs.csv | sed 's/\t/: [/' | sed 's/\t/, /' | sed 's/$/],/' > 90_rs.cjs
sed 's/,/./g' 120_rs.csv | sed 's/\t/: [/' | sed 's/\t/, /' | sed 's/$/],/' > 120_rs.cjs
